"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import Sessionprovider from "@/providers/sessionProvider";
import Sidebar from "@/components/sidebar";
import Asidebar from "@/components/asidebar";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "cloud storage",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sessionprovider>
          {pathname === "/signup" ? (
            <div>{children}</div>
          ) : (
            <main className="w-full h-screen flex flex-row">
              <Sidebar />
              <div className="flex w-full">
                <div className="flex-1 bg-blue-50 py-4 px-5">{children}</div>
                <div className="flex-[.5] border-l p-5 shadow-sm">
                  <Asidebar />
                </div>
              </div>
            </main>
          )}
        </Sessionprovider>
      </body>
    </html>
  );
}
